model:
  model_name: "/home/ge.polymtl.ca/p123239/.cache/huggingface/hub/models--raidium--curia/snapshots/9657dc56276bc6c9503ef6f8d060879c8bee482f"
  num_classes: 3
  head_type: "linear"

data_dir: "/home/ge.polymtl.ca/p123239/data/RSNA_patches_scs"

fold_split_csv: "/home/ge.polymtl.ca/p123239/fold_split_RSNA.json"
fold_column: "regime_all_split_1_set"

epochs: 50
batch_size: 256
learning_rate: 0.001
weight_decay: 0.0001
num_workers: 4
eval_steps: 4

cache_suffix: "curia_crop4cm_cls"
use_feature_caching: true
use_class_weights: true

task: "scs"
log_dir: "/home/ge.polymtl.ca/p123239/SpineFoundation/classification_hf/logs"
output_dir: "/home/ge.polymtl.ca/p123239/SpineFoundation/outputs_cls/rsna_scs_crop4cm_cls"
