model:
  model_name: "/home/ge.polymtl.ca/p123239/.cache/huggingface/hub/models--raidium--curia/snapshots/9657dc56276bc6c9503ef6f8d060879c8bee482f"
  subfolder: "spinal_canal_stenosis"
  num_classes: 3
  attention_cfg: null

data_dir: "/home/ge.polymtl.ca/p123239/data/RSNA_patches_scs"
val_split: 0.15
seed: 42

epochs: 25
batch_size: 512
learning_rate: 0.005
weight_decay: 0.0001
num_workers: 8
eval_steps: 4

use_feature_caching: true

cache_suffix: "spine_only"    # → pooled_features_spine_only_dil0.pt

task: "scs"
log_dir: "/home/ge.polymtl.ca/p123239/SpineFoundation/classification_hf/logs_custom"
output_dir: "/home/ge.polymtl.ca/p123239/SpineFoundation/outputs_cls/rsna_scs_spine_only"
use_pretrained_head: false
